# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160902_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
